AWSTemplateFormatVersion: 2010-09-09
Description: ---
Parameters:
  bucketName:
    Type: String
    Description: Name of the S3 bucket
    
Resources: 
  networkingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
         TemplateURL: !Sub https://s3.amazonaws.com/${bucketName}/networking.yaml

  databaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
         TemplateURL: !Sub https://s3.amazonaws.com/${bucketName}/database.yaml

  computeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
         - networkingStack
    Properties:
         TemplateURL: !Sub https://s3.amazonaws.com/${bucketName}/compute.yaml