AWSTemplateFormatVersion: 2010-09-09
Description: Deploying an RDS instance

Resources:
  myDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: My DB Subnet Group
      SubnetIds:
        - !ImportValue privateSubnet1Id
        - !ImportValue privateSubnet2Id

  primaryDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: mydatabase
      Engine: mysql
      MasterUsername: myusername
      MasterUserPassword: mypassword
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 5
      BackupRetentionPeriod: 7
      MultiAZ: true
      DBSubnetGroupName: !Ref myDBSubnetGroup
      VPCSecurityGroups:
           - !ImportValue dbSG

Outputs:
  primaryDBEndpoint:
    Description: The endpoint of the primary DB instance
    Value: !GetAtt primaryDBInstance.Endpoint.Address
