AWSTemplateFormatVersion: 2010-09-09
Description: ---
Resources: 
  dynamodbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "myDynamoDB"
      ProvisionedThroughput:
           ReadCapacityUnits: "5"
           WriteCapacityUnits: "5"
      AttributeDefinitions:
           - AttributeName: "Music"
             AttributeType: "S"
           - AttributeName: "Concert"
             AttributeType: "S"
      KeySchema:
        - 
          AttributeName: "Music"
          KeyType: "HASH"
        -
          AttributeName: "Concert"
          KeyType: "RANGE"
      Tags:
        - Key: key
          Value: value
